# Generated by Django 5.2.3 on 2025-06-26 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertastock',
            name='vista_por',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Vista por usuarios'),
        ),
        migrations.AddField(
            model_name='alertastock',
            name='pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pieza', verbose_name='Pieza'),
        ),
    ]
