# Generated by Django 5.2.3 on 2025-09-11 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de última modificación'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='ultima_modificacion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Última modificación por'),
        ),
    ]
