# Generated by Django 5.2.3 on 2025-06-26 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10, verbose_name='Tipo de movimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del movimiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('stock_anterior', models.PositiveIntegerField(verbose_name='Stock anterior')),
                ('stock_posterior', models.PositiveIntegerField(verbose_name='Stock posterior')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pieza', verbose_name='Pieza')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
